version: '3.8'
services:
  airport:
    container_name: airport
    build:
      context: .
      target: development
    env_file:
      - src/main/resources/docker.env
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app
    networks:
      - bridge
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.2
    env_file:
      - src/main/resources/docker.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgres
      - postgres_config:/etc/postgres/conf.d
    networks:
      - bridge

volumes:
  postgres_data:
  postgres_config:

networks:
  bridge:
    driver: bridge
