CREATE TABLE IF NOT EXISTS "User" (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(300) NOT NULL UNIQUE,
    authority varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Airplane (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model varchar(300) NOT NULL UNIQUE,
    seat_amount smallint NOT NULL
);